puts "The translator works if everything below prints true:"
puts translate("I'm gonna study algebra") == "I'm gonna dance to Top 40 hits while singing into a hairbrush"
puts translate("Got an A on my test") == "Got asked to prom by a dreamy Ruby-programming senior"
puts translate("Tonight's debate team meeting will be awesome") == "Our secret warehouse hackathon in which we write software aiding us in conspiring against our parents will be awesome"
puts translate("I love my parents!") == "My parents drive me crazy, but I really do love them. Mostly."
